# Generated by Django 5.2.7 on 2025-11-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('support', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province'),
        ),
    ]
