# Generated by Django 5.2.8 on 2025-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unread_for_assignee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unread_for_creator',
            field=models.BooleanField(default=False),
        ),
    ]
