# Generated by Django 5.2.8 on 2025-11-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_seed_provinces'),
        ('support', '0006_ticket_unread_for_assignee_ticket_unread_for_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='shops.spazashop'),
        ),
    ]
