# Generated by Django 5.2.7 on 2025-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('COR_REG', 'Business Reg'), ('TAX', 'Tax Compliance'), ('COA', 'Health/COA'), ('BUSINESS_LICENCE', 'Business Licence / Trading Permit'), ('FIRE_SAFETY', 'Fire Safety Certificate'), ('OTHER', 'Other Supporting Documents')], max_length=50),
        ),
    ]
