# Generated by Django 5.2.7 on 2025-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('ID_PERMIT', 'Certified ID/Passport/Permit'), ('BUSINESS_LICENSE', 'Business Licence / Trading Permit'), ('FIRE_SAFETY', 'Fire Safety Certificate'), ('OWNERSHIP_PROOF', 'Proof of Property Ownership/Lease'), ('BANK_CONFIRMATION', 'Bank Confirmation Letter'), ('BUSINESS_REGISTRATION', 'Business Registration Certificate'), ('HEALTH_CERTIFICATE', 'Certificate of Acceptability (Health)'), ('SARS_DOCUMENTS', 'Tax / SARS Documents'), ('OTHER', 'Other Supporting Documents')], max_length=50),
        ),
    ]
