# Generated by Django 5.2.7 on 2025-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('COR_REG', 'Business Registration Certificate'), ('COA', 'Certificate of Acceptability (Health)'), ('TAX', 'Tax / SARS Documents'), ('ID_PERMIT', 'Certified ID/Passport/Permit'), ('BUSINESS_LICENSE', 'Business Licence / Trading Permit'), ('FIRE_SAFETY', 'Fire Safety Certificate'), ('PROOF_OF_PROPERTY', 'Proof of Property Ownership/Lease'), ('BANK_LETTER', 'Bank Confirmation Letter'), ('OTHER', 'Other Supporting Documents')], max_length=50),
        ),
    ]
