# Generated by Django 5.2.7 on 2025-10-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitform',
            name='adequate_ventilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='building_plan_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='food_labels_and_expiry_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='healthy_storage_goods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='inventory_system_in_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='notices_policies_displayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='prices_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='refund_policy_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='sales_record_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='supplier_list_present',
            field=models.BooleanField(default=False),
        ),
    ]
