# Generated by Django 5.2.7 on 2025-11-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_sitevisitform_adequate_ventilation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitform',
            name='contractor_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitevisitform',
            name='inspector_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
