# Generated by Django 5.2.7 on 2025-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_sitevisitform_contractor_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='share_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='share_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30),
        ),
    ]
